# This is a workflow that is manually triggered. It displays a USER environment variable, a secret PASSKEY, and a Greeting variable

name: Environments and Secrets

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: dev

    env:
      Greeting: Hi

    steps:

    - name: user from dev
      run: echo "$Greeting ${{ vars.USER }}"

    - name: passkey from dev
      run: echo "Here is your passkey ${{ secrets.PASSKEY }}"
