name: sample action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      message:
        description: 'A sample input'
        required: true
        default: 'Use workflow_dispatch to run this workflow'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script on push or PR events
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: echo "GitHub says hello!"

      - name: Run a one-line script on workflow_dispatch event with an input
        if: github.event_name == 'workflow_dispatch'
        run: echo ${{ github.event.inputs.message }}

      - name: Run a multi-line script
        run: |
            echo "Add other actions to build,"
            echo "test, and deploy your project."


