name: script welcome

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      welcome_message: 
        description: "this message is delivered to a script as an environment variable"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      repo_owner: ${{ github.repository_owner }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: chkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - id: oneline
        name: Run a sample script
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ inputs.welcome_message }}
        run: chmod +x .github/scripts/sample.sh  && .github/scripts/sample.sh
