# This action checks out your code, sets up Node.js, and runs npm install and npm test.

name: 'Setup and Test'
description: 'Checks out code, sets up Node.js, and runs npm install and npm test'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '14'
runs:
  using: 'composite'
  steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run tests
      run: npm test
      shell: bash